---

- name: create directory structure
  win_file:
    path: C:\SEPM-Win
    state: directory

- name: download SEPM binary
  win_get_url:
    url: http://{{ repourl }}/Binaries/{{ ansible_hostname[:3] | lower }}/latest/win/setup.exe
    dest: C:\SEPM-Win\setup.exe
  register: download_result
  retries: 10
  until: download_result.status_code is defined and download_result.status_code == 200

- name: execute sepm-win.exe
  win_shell: Start-Process -FilePath "setup.exe" -Verb runAs -Wait
  args:
    chdir: C:\SEPM-Win

- name: reboot the VM
  win_reboot:
  ignore_errors: true

- name: wait for ports to open
  wait_for:
    host: "{{ ansible_host | default(inventory_hostname }}"
    port: "{{ ansible_port | default(5985)}}"
    state: started
  delegate_to: localhost

- name: check Syamntec endpoint protection installed or not
  win_service:
    name: Symantec Endpoint Protection
    state: started
