---
# This playbook deletes the Kubernetes configuration from all nodes
# It removes the Kubernetes repository, uninstalls related packages, and deletes required files

- hosts: all
  vars:
    packages:
      - docker*
      - kubeadm
      - kubectl
      - kubelet
  tasks:
    - name: removing repo file of k8
      file:
        path: /etc/yum.repos.d/kubernetes.repo
        state: absent

- hosts: all 
  vars:
    packages:
      - docker*
      - kubeadm
      - kubectl
      - kubelet
  tasks:
    - name: removing repo file of k8
      file:
        path: /etc/yum.repos.d/kubernetes.repo
        state: absent

    - name: removing/uninstalling k8s related packages
      yum:
        name: "{{ item }}"
        state: absent
      with_items: "{{packages}}"

    - name: removing required files
      file:
        path: "{{item}}"
        state: absent
      with_items:
        - /etc/kubernetes/
        - /var/lib/etcd/
        - $HOME/.kube/